name: blbl
description: "哔哩哔哩"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1 # 网络请求
  # 视频播放（适配鸿蒙）
  video_player:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_packages.git"
      path: "packages/video_player/video_player"
  # 跨平台视频播放支持
  media_kit: ^1.1.10                  # 核心包
  media_kit_video: ^1.2.4             # 视频渲染
  media_kit_libs_windows_video: ^1.0.9 # Windows平台支持

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
