name: blbl
description: "哔哩哔哩"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1 # 网络请求
  media_kit: ^1.2.0 # Windows视频播放核心包
  media_kit_video: ^1.3.0 # Windows视频渲染
  media_kit_libs_windows_video: ^1.0.11 # Windows视频播放
  video_player: # 视频播放鸿蒙适配版
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_packages.git"
      path: "packages/video_player/video_player"
  shared_preferences: # 本地存储鸿蒙适配版
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
  qr_flutter: ^4.1.0 # 二维码

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
